# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/media/manan-sharma/New Volume/IIIT/4-1/Compilers/project/decaff-compiler-manan180796"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/media/manan-sharma/New Volume/IIIT/4-1/Compilers/project/decaff-compiler-manan180796"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/manan-sharma/New Volume/IIIT/4-1/Compilers/project/decaff-compiler-manan180796/CMakeFiles" "/media/manan-sharma/New Volume/IIIT/4-1/Compilers/project/decaff-compiler-manan180796/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/manan-sharma/New Volume/IIIT/4-1/Compilers/project/decaff-compiler-manan180796/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named decafCompiler

# Build rule for target.
decafCompiler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 decafCompiler
.PHONY : decafCompiler

# fast build rule for target.
decafCompiler/fast:
	$(MAKE) -f CMakeFiles/decafCompiler.dir/build.make CMakeFiles/decafCompiler.dir/build
.PHONY : decafCompiler/fast

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named coreLibrary

# Build rule for target.
coreLibrary: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coreLibrary
.PHONY : coreLibrary

# fast build rule for target.
coreLibrary/fast:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/build
.PHONY : coreLibrary/fast

flex_bison_output/lex.yy.o: flex_bison_output/lex.yy.c.o

.PHONY : flex_bison_output/lex.yy.o

# target to build an object file
flex_bison_output/lex.yy.c.o:
	$(MAKE) -f CMakeFiles/decafCompiler.dir/build.make CMakeFiles/decafCompiler.dir/flex_bison_output/lex.yy.c.o
.PHONY : flex_bison_output/lex.yy.c.o

flex_bison_output/lex.yy.i: flex_bison_output/lex.yy.c.i

.PHONY : flex_bison_output/lex.yy.i

# target to preprocess a source file
flex_bison_output/lex.yy.c.i:
	$(MAKE) -f CMakeFiles/decafCompiler.dir/build.make CMakeFiles/decafCompiler.dir/flex_bison_output/lex.yy.c.i
.PHONY : flex_bison_output/lex.yy.c.i

flex_bison_output/lex.yy.s: flex_bison_output/lex.yy.c.s

.PHONY : flex_bison_output/lex.yy.s

# target to generate assembly for a file
flex_bison_output/lex.yy.c.s:
	$(MAKE) -f CMakeFiles/decafCompiler.dir/build.make CMakeFiles/decafCompiler.dir/flex_bison_output/lex.yy.c.s
.PHONY : flex_bison_output/lex.yy.c.s

flex_bison_output/parser.tab.o: flex_bison_output/parser.tab.c.o

.PHONY : flex_bison_output/parser.tab.o

# target to build an object file
flex_bison_output/parser.tab.c.o:
	$(MAKE) -f CMakeFiles/decafCompiler.dir/build.make CMakeFiles/decafCompiler.dir/flex_bison_output/parser.tab.c.o
.PHONY : flex_bison_output/parser.tab.c.o

flex_bison_output/parser.tab.i: flex_bison_output/parser.tab.c.i

.PHONY : flex_bison_output/parser.tab.i

# target to preprocess a source file
flex_bison_output/parser.tab.c.i:
	$(MAKE) -f CMakeFiles/decafCompiler.dir/build.make CMakeFiles/decafCompiler.dir/flex_bison_output/parser.tab.c.i
.PHONY : flex_bison_output/parser.tab.c.i

flex_bison_output/parser.tab.s: flex_bison_output/parser.tab.c.s

.PHONY : flex_bison_output/parser.tab.s

# target to generate assembly for a file
flex_bison_output/parser.tab.c.s:
	$(MAKE) -f CMakeFiles/decafCompiler.dir/build.make CMakeFiles/decafCompiler.dir/flex_bison_output/parser.tab.c.s
.PHONY : flex_bison_output/parser.tab.c.s

src/ArgumentDeclaration.o: src/ArgumentDeclaration.cpp.o

.PHONY : src/ArgumentDeclaration.o

# target to build an object file
src/ArgumentDeclaration.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/ArgumentDeclaration.cpp.o
.PHONY : src/ArgumentDeclaration.cpp.o

src/ArgumentDeclaration.i: src/ArgumentDeclaration.cpp.i

.PHONY : src/ArgumentDeclaration.i

# target to preprocess a source file
src/ArgumentDeclaration.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/ArgumentDeclaration.cpp.i
.PHONY : src/ArgumentDeclaration.cpp.i

src/ArgumentDeclaration.s: src/ArgumentDeclaration.cpp.s

.PHONY : src/ArgumentDeclaration.s

# target to generate assembly for a file
src/ArgumentDeclaration.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/ArgumentDeclaration.cpp.s
.PHONY : src/ArgumentDeclaration.cpp.s

src/ArgumentDeclarationList.o: src/ArgumentDeclarationList.cpp.o

.PHONY : src/ArgumentDeclarationList.o

# target to build an object file
src/ArgumentDeclarationList.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/ArgumentDeclarationList.cpp.o
.PHONY : src/ArgumentDeclarationList.cpp.o

src/ArgumentDeclarationList.i: src/ArgumentDeclarationList.cpp.i

.PHONY : src/ArgumentDeclarationList.i

# target to preprocess a source file
src/ArgumentDeclarationList.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/ArgumentDeclarationList.cpp.i
.PHONY : src/ArgumentDeclarationList.cpp.i

src/ArgumentDeclarationList.s: src/ArgumentDeclarationList.cpp.s

.PHONY : src/ArgumentDeclarationList.s

# target to generate assembly for a file
src/ArgumentDeclarationList.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/ArgumentDeclarationList.cpp.s
.PHONY : src/ArgumentDeclarationList.cpp.s

src/AssignmentStatement.o: src/AssignmentStatement.cpp.o

.PHONY : src/AssignmentStatement.o

# target to build an object file
src/AssignmentStatement.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/AssignmentStatement.cpp.o
.PHONY : src/AssignmentStatement.cpp.o

src/AssignmentStatement.i: src/AssignmentStatement.cpp.i

.PHONY : src/AssignmentStatement.i

# target to preprocess a source file
src/AssignmentStatement.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/AssignmentStatement.cpp.i
.PHONY : src/AssignmentStatement.cpp.i

src/AssignmentStatement.s: src/AssignmentStatement.cpp.s

.PHONY : src/AssignmentStatement.s

# target to generate assembly for a file
src/AssignmentStatement.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/AssignmentStatement.cpp.s
.PHONY : src/AssignmentStatement.cpp.s

src/BinaryExpression.o: src/BinaryExpression.cpp.o

.PHONY : src/BinaryExpression.o

# target to build an object file
src/BinaryExpression.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/BinaryExpression.cpp.o
.PHONY : src/BinaryExpression.cpp.o

src/BinaryExpression.i: src/BinaryExpression.cpp.i

.PHONY : src/BinaryExpression.i

# target to preprocess a source file
src/BinaryExpression.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/BinaryExpression.cpp.i
.PHONY : src/BinaryExpression.cpp.i

src/BinaryExpression.s: src/BinaryExpression.cpp.s

.PHONY : src/BinaryExpression.s

# target to generate assembly for a file
src/BinaryExpression.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/BinaryExpression.cpp.s
.PHONY : src/BinaryExpression.cpp.s

src/Block.o: src/Block.cpp.o

.PHONY : src/Block.o

# target to build an object file
src/Block.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/Block.cpp.o
.PHONY : src/Block.cpp.o

src/Block.i: src/Block.cpp.i

.PHONY : src/Block.i

# target to preprocess a source file
src/Block.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/Block.cpp.i
.PHONY : src/Block.cpp.i

src/Block.s: src/Block.cpp.s

.PHONY : src/Block.s

# target to generate assembly for a file
src/Block.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/Block.cpp.s
.PHONY : src/Block.cpp.s

src/BoolLiteral.o: src/BoolLiteral.cpp.o

.PHONY : src/BoolLiteral.o

# target to build an object file
src/BoolLiteral.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/BoolLiteral.cpp.o
.PHONY : src/BoolLiteral.cpp.o

src/BoolLiteral.i: src/BoolLiteral.cpp.i

.PHONY : src/BoolLiteral.i

# target to preprocess a source file
src/BoolLiteral.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/BoolLiteral.cpp.i
.PHONY : src/BoolLiteral.cpp.i

src/BoolLiteral.s: src/BoolLiteral.cpp.s

.PHONY : src/BoolLiteral.s

# target to generate assembly for a file
src/BoolLiteral.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/BoolLiteral.cpp.s
.PHONY : src/BoolLiteral.cpp.s

src/BreakStatement.o: src/BreakStatement.cpp.o

.PHONY : src/BreakStatement.o

# target to build an object file
src/BreakStatement.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/BreakStatement.cpp.o
.PHONY : src/BreakStatement.cpp.o

src/BreakStatement.i: src/BreakStatement.cpp.i

.PHONY : src/BreakStatement.i

# target to preprocess a source file
src/BreakStatement.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/BreakStatement.cpp.i
.PHONY : src/BreakStatement.cpp.i

src/BreakStatement.s: src/BreakStatement.cpp.s

.PHONY : src/BreakStatement.s

# target to generate assembly for a file
src/BreakStatement.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/BreakStatement.cpp.s
.PHONY : src/BreakStatement.cpp.s

src/CalloutArg.o: src/CalloutArg.cpp.o

.PHONY : src/CalloutArg.o

# target to build an object file
src/CalloutArg.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/CalloutArg.cpp.o
.PHONY : src/CalloutArg.cpp.o

src/CalloutArg.i: src/CalloutArg.cpp.i

.PHONY : src/CalloutArg.i

# target to preprocess a source file
src/CalloutArg.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/CalloutArg.cpp.i
.PHONY : src/CalloutArg.cpp.i

src/CalloutArg.s: src/CalloutArg.cpp.s

.PHONY : src/CalloutArg.s

# target to generate assembly for a file
src/CalloutArg.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/CalloutArg.cpp.s
.PHONY : src/CalloutArg.cpp.s

src/CalloutArgList.o: src/CalloutArgList.cpp.o

.PHONY : src/CalloutArgList.o

# target to build an object file
src/CalloutArgList.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/CalloutArgList.cpp.o
.PHONY : src/CalloutArgList.cpp.o

src/CalloutArgList.i: src/CalloutArgList.cpp.i

.PHONY : src/CalloutArgList.i

# target to preprocess a source file
src/CalloutArgList.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/CalloutArgList.cpp.i
.PHONY : src/CalloutArgList.cpp.i

src/CalloutArgList.s: src/CalloutArgList.cpp.s

.PHONY : src/CalloutArgList.s

# target to generate assembly for a file
src/CalloutArgList.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/CalloutArgList.cpp.s
.PHONY : src/CalloutArgList.cpp.s

src/CalloutMethod.o: src/CalloutMethod.cpp.o

.PHONY : src/CalloutMethod.o

# target to build an object file
src/CalloutMethod.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/CalloutMethod.cpp.o
.PHONY : src/CalloutMethod.cpp.o

src/CalloutMethod.i: src/CalloutMethod.cpp.i

.PHONY : src/CalloutMethod.i

# target to preprocess a source file
src/CalloutMethod.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/CalloutMethod.cpp.i
.PHONY : src/CalloutMethod.cpp.i

src/CalloutMethod.s: src/CalloutMethod.cpp.s

.PHONY : src/CalloutMethod.s

# target to generate assembly for a file
src/CalloutMethod.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/CalloutMethod.cpp.s
.PHONY : src/CalloutMethod.cpp.s

src/CharLiteral.o: src/CharLiteral.cpp.o

.PHONY : src/CharLiteral.o

# target to build an object file
src/CharLiteral.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/CharLiteral.cpp.o
.PHONY : src/CharLiteral.cpp.o

src/CharLiteral.i: src/CharLiteral.cpp.i

.PHONY : src/CharLiteral.i

# target to preprocess a source file
src/CharLiteral.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/CharLiteral.cpp.i
.PHONY : src/CharLiteral.cpp.i

src/CharLiteral.s: src/CharLiteral.cpp.s

.PHONY : src/CharLiteral.s

# target to generate assembly for a file
src/CharLiteral.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/CharLiteral.cpp.s
.PHONY : src/CharLiteral.cpp.s

src/ContinueStatement.o: src/ContinueStatement.cpp.o

.PHONY : src/ContinueStatement.o

# target to build an object file
src/ContinueStatement.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/ContinueStatement.cpp.o
.PHONY : src/ContinueStatement.cpp.o

src/ContinueStatement.i: src/ContinueStatement.cpp.i

.PHONY : src/ContinueStatement.i

# target to preprocess a source file
src/ContinueStatement.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/ContinueStatement.cpp.i
.PHONY : src/ContinueStatement.cpp.i

src/ContinueStatement.s: src/ContinueStatement.cpp.s

.PHONY : src/ContinueStatement.s

# target to generate assembly for a file
src/ContinueStatement.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/ContinueStatement.cpp.s
.PHONY : src/ContinueStatement.cpp.s

src/Expression.o: src/Expression.cpp.o

.PHONY : src/Expression.o

# target to build an object file
src/Expression.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/Expression.cpp.o
.PHONY : src/Expression.cpp.o

src/Expression.i: src/Expression.cpp.i

.PHONY : src/Expression.i

# target to preprocess a source file
src/Expression.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/Expression.cpp.i
.PHONY : src/Expression.cpp.i

src/Expression.s: src/Expression.cpp.s

.PHONY : src/Expression.s

# target to generate assembly for a file
src/Expression.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/Expression.cpp.s
.PHONY : src/Expression.cpp.s

src/ExpressionList.o: src/ExpressionList.cpp.o

.PHONY : src/ExpressionList.o

# target to build an object file
src/ExpressionList.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/ExpressionList.cpp.o
.PHONY : src/ExpressionList.cpp.o

src/ExpressionList.i: src/ExpressionList.cpp.i

.PHONY : src/ExpressionList.i

# target to preprocess a source file
src/ExpressionList.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/ExpressionList.cpp.i
.PHONY : src/ExpressionList.cpp.i

src/ExpressionList.s: src/ExpressionList.cpp.s

.PHONY : src/ExpressionList.s

# target to generate assembly for a file
src/ExpressionList.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/ExpressionList.cpp.s
.PHONY : src/ExpressionList.cpp.s

src/Field.o: src/Field.cpp.o

.PHONY : src/Field.o

# target to build an object file
src/Field.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/Field.cpp.o
.PHONY : src/Field.cpp.o

src/Field.i: src/Field.cpp.i

.PHONY : src/Field.i

# target to preprocess a source file
src/Field.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/Field.cpp.i
.PHONY : src/Field.cpp.i

src/Field.s: src/Field.cpp.s

.PHONY : src/Field.s

# target to generate assembly for a file
src/Field.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/Field.cpp.s
.PHONY : src/Field.cpp.s

src/FieldDeclaration.o: src/FieldDeclaration.cpp.o

.PHONY : src/FieldDeclaration.o

# target to build an object file
src/FieldDeclaration.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/FieldDeclaration.cpp.o
.PHONY : src/FieldDeclaration.cpp.o

src/FieldDeclaration.i: src/FieldDeclaration.cpp.i

.PHONY : src/FieldDeclaration.i

# target to preprocess a source file
src/FieldDeclaration.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/FieldDeclaration.cpp.i
.PHONY : src/FieldDeclaration.cpp.i

src/FieldDeclaration.s: src/FieldDeclaration.cpp.s

.PHONY : src/FieldDeclaration.s

# target to generate assembly for a file
src/FieldDeclaration.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/FieldDeclaration.cpp.s
.PHONY : src/FieldDeclaration.cpp.s

src/FieldDeclarationList.o: src/FieldDeclarationList.cpp.o

.PHONY : src/FieldDeclarationList.o

# target to build an object file
src/FieldDeclarationList.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/FieldDeclarationList.cpp.o
.PHONY : src/FieldDeclarationList.cpp.o

src/FieldDeclarationList.i: src/FieldDeclarationList.cpp.i

.PHONY : src/FieldDeclarationList.i

# target to preprocess a source file
src/FieldDeclarationList.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/FieldDeclarationList.cpp.i
.PHONY : src/FieldDeclarationList.cpp.i

src/FieldDeclarationList.s: src/FieldDeclarationList.cpp.s

.PHONY : src/FieldDeclarationList.s

# target to generate assembly for a file
src/FieldDeclarationList.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/FieldDeclarationList.cpp.s
.PHONY : src/FieldDeclarationList.cpp.s

src/FieldList.o: src/FieldList.cpp.o

.PHONY : src/FieldList.o

# target to build an object file
src/FieldList.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/FieldList.cpp.o
.PHONY : src/FieldList.cpp.o

src/FieldList.i: src/FieldList.cpp.i

.PHONY : src/FieldList.i

# target to preprocess a source file
src/FieldList.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/FieldList.cpp.i
.PHONY : src/FieldList.cpp.i

src/FieldList.s: src/FieldList.cpp.s

.PHONY : src/FieldList.s

# target to generate assembly for a file
src/FieldList.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/FieldList.cpp.s
.PHONY : src/FieldList.cpp.s

src/ForStatement.o: src/ForStatement.cpp.o

.PHONY : src/ForStatement.o

# target to build an object file
src/ForStatement.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/ForStatement.cpp.o
.PHONY : src/ForStatement.cpp.o

src/ForStatement.i: src/ForStatement.cpp.i

.PHONY : src/ForStatement.i

# target to preprocess a source file
src/ForStatement.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/ForStatement.cpp.i
.PHONY : src/ForStatement.cpp.i

src/ForStatement.s: src/ForStatement.cpp.s

.PHONY : src/ForStatement.s

# target to generate assembly for a file
src/ForStatement.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/ForStatement.cpp.s
.PHONY : src/ForStatement.cpp.s

src/IdList.o: src/IdList.cpp.o

.PHONY : src/IdList.o

# target to build an object file
src/IdList.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/IdList.cpp.o
.PHONY : src/IdList.cpp.o

src/IdList.i: src/IdList.cpp.i

.PHONY : src/IdList.i

# target to preprocess a source file
src/IdList.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/IdList.cpp.i
.PHONY : src/IdList.cpp.i

src/IdList.s: src/IdList.cpp.s

.PHONY : src/IdList.s

# target to generate assembly for a file
src/IdList.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/IdList.cpp.s
.PHONY : src/IdList.cpp.s

src/IfStatement.o: src/IfStatement.cpp.o

.PHONY : src/IfStatement.o

# target to build an object file
src/IfStatement.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/IfStatement.cpp.o
.PHONY : src/IfStatement.cpp.o

src/IfStatement.i: src/IfStatement.cpp.i

.PHONY : src/IfStatement.i

# target to preprocess a source file
src/IfStatement.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/IfStatement.cpp.i
.PHONY : src/IfStatement.cpp.i

src/IfStatement.s: src/IfStatement.cpp.s

.PHONY : src/IfStatement.s

# target to generate assembly for a file
src/IfStatement.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/IfStatement.cpp.s
.PHONY : src/IfStatement.cpp.s

src/IntLiteral.o: src/IntLiteral.cpp.o

.PHONY : src/IntLiteral.o

# target to build an object file
src/IntLiteral.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/IntLiteral.cpp.o
.PHONY : src/IntLiteral.cpp.o

src/IntLiteral.i: src/IntLiteral.cpp.i

.PHONY : src/IntLiteral.i

# target to preprocess a source file
src/IntLiteral.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/IntLiteral.cpp.i
.PHONY : src/IntLiteral.cpp.i

src/IntLiteral.s: src/IntLiteral.cpp.s

.PHONY : src/IntLiteral.s

# target to generate assembly for a file
src/IntLiteral.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/IntLiteral.cpp.s
.PHONY : src/IntLiteral.cpp.s

src/LLVMIRGenerator.o: src/LLVMIRGenerator.cpp.o

.PHONY : src/LLVMIRGenerator.o

# target to build an object file
src/LLVMIRGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/LLVMIRGenerator.cpp.o
.PHONY : src/LLVMIRGenerator.cpp.o

src/LLVMIRGenerator.i: src/LLVMIRGenerator.cpp.i

.PHONY : src/LLVMIRGenerator.i

# target to preprocess a source file
src/LLVMIRGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/LLVMIRGenerator.cpp.i
.PHONY : src/LLVMIRGenerator.cpp.i

src/LLVMIRGenerator.s: src/LLVMIRGenerator.cpp.s

.PHONY : src/LLVMIRGenerator.s

# target to generate assembly for a file
src/LLVMIRGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/LLVMIRGenerator.cpp.s
.PHONY : src/LLVMIRGenerator.cpp.s

src/Location.o: src/Location.cpp.o

.PHONY : src/Location.o

# target to build an object file
src/Location.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/Location.cpp.o
.PHONY : src/Location.cpp.o

src/Location.i: src/Location.cpp.i

.PHONY : src/Location.i

# target to preprocess a source file
src/Location.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/Location.cpp.i
.PHONY : src/Location.cpp.i

src/Location.s: src/Location.cpp.s

.PHONY : src/Location.s

# target to generate assembly for a file
src/Location.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/Location.cpp.s
.PHONY : src/Location.cpp.s

src/MethodDeclaration.o: src/MethodDeclaration.cpp.o

.PHONY : src/MethodDeclaration.o

# target to build an object file
src/MethodDeclaration.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/MethodDeclaration.cpp.o
.PHONY : src/MethodDeclaration.cpp.o

src/MethodDeclaration.i: src/MethodDeclaration.cpp.i

.PHONY : src/MethodDeclaration.i

# target to preprocess a source file
src/MethodDeclaration.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/MethodDeclaration.cpp.i
.PHONY : src/MethodDeclaration.cpp.i

src/MethodDeclaration.s: src/MethodDeclaration.cpp.s

.PHONY : src/MethodDeclaration.s

# target to generate assembly for a file
src/MethodDeclaration.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/MethodDeclaration.cpp.s
.PHONY : src/MethodDeclaration.cpp.s

src/MethodDeclarationList.o: src/MethodDeclarationList.cpp.o

.PHONY : src/MethodDeclarationList.o

# target to build an object file
src/MethodDeclarationList.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/MethodDeclarationList.cpp.o
.PHONY : src/MethodDeclarationList.cpp.o

src/MethodDeclarationList.i: src/MethodDeclarationList.cpp.i

.PHONY : src/MethodDeclarationList.i

# target to preprocess a source file
src/MethodDeclarationList.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/MethodDeclarationList.cpp.i
.PHONY : src/MethodDeclarationList.cpp.i

src/MethodDeclarationList.s: src/MethodDeclarationList.cpp.s

.PHONY : src/MethodDeclarationList.s

# target to generate assembly for a file
src/MethodDeclarationList.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/MethodDeclarationList.cpp.s
.PHONY : src/MethodDeclarationList.cpp.s

src/MethodStatement.o: src/MethodStatement.cpp.o

.PHONY : src/MethodStatement.o

# target to build an object file
src/MethodStatement.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/MethodStatement.cpp.o
.PHONY : src/MethodStatement.cpp.o

src/MethodStatement.i: src/MethodStatement.cpp.i

.PHONY : src/MethodStatement.i

# target to preprocess a source file
src/MethodStatement.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/MethodStatement.cpp.i
.PHONY : src/MethodStatement.cpp.i

src/MethodStatement.s: src/MethodStatement.cpp.s

.PHONY : src/MethodStatement.s

# target to generate assembly for a file
src/MethodStatement.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/MethodStatement.cpp.s
.PHONY : src/MethodStatement.cpp.s

src/NestedUnaryExpression.o: src/NestedUnaryExpression.cpp.o

.PHONY : src/NestedUnaryExpression.o

# target to build an object file
src/NestedUnaryExpression.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/NestedUnaryExpression.cpp.o
.PHONY : src/NestedUnaryExpression.cpp.o

src/NestedUnaryExpression.i: src/NestedUnaryExpression.cpp.i

.PHONY : src/NestedUnaryExpression.i

# target to preprocess a source file
src/NestedUnaryExpression.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/NestedUnaryExpression.cpp.i
.PHONY : src/NestedUnaryExpression.cpp.i

src/NestedUnaryExpression.s: src/NestedUnaryExpression.cpp.s

.PHONY : src/NestedUnaryExpression.s

# target to generate assembly for a file
src/NestedUnaryExpression.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/NestedUnaryExpression.cpp.s
.PHONY : src/NestedUnaryExpression.cpp.s

src/Program.o: src/Program.cpp.o

.PHONY : src/Program.o

# target to build an object file
src/Program.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/Program.cpp.o
.PHONY : src/Program.cpp.o

src/Program.i: src/Program.cpp.i

.PHONY : src/Program.i

# target to preprocess a source file
src/Program.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/Program.cpp.i
.PHONY : src/Program.cpp.i

src/Program.s: src/Program.cpp.s

.PHONY : src/Program.s

# target to generate assembly for a file
src/Program.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/Program.cpp.s
.PHONY : src/Program.cpp.s

src/ReturnExpression.o: src/ReturnExpression.cpp.o

.PHONY : src/ReturnExpression.o

# target to build an object file
src/ReturnExpression.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/ReturnExpression.cpp.o
.PHONY : src/ReturnExpression.cpp.o

src/ReturnExpression.i: src/ReturnExpression.cpp.i

.PHONY : src/ReturnExpression.i

# target to preprocess a source file
src/ReturnExpression.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/ReturnExpression.cpp.i
.PHONY : src/ReturnExpression.cpp.i

src/ReturnExpression.s: src/ReturnExpression.cpp.s

.PHONY : src/ReturnExpression.s

# target to generate assembly for a file
src/ReturnExpression.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/ReturnExpression.cpp.s
.PHONY : src/ReturnExpression.cpp.s

src/SimpleMethod.o: src/SimpleMethod.cpp.o

.PHONY : src/SimpleMethod.o

# target to build an object file
src/SimpleMethod.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/SimpleMethod.cpp.o
.PHONY : src/SimpleMethod.cpp.o

src/SimpleMethod.i: src/SimpleMethod.cpp.i

.PHONY : src/SimpleMethod.i

# target to preprocess a source file
src/SimpleMethod.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/SimpleMethod.cpp.i
.PHONY : src/SimpleMethod.cpp.i

src/SimpleMethod.s: src/SimpleMethod.cpp.s

.PHONY : src/SimpleMethod.s

# target to generate assembly for a file
src/SimpleMethod.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/SimpleMethod.cpp.s
.PHONY : src/SimpleMethod.cpp.s

src/StatementList.o: src/StatementList.cpp.o

.PHONY : src/StatementList.o

# target to build an object file
src/StatementList.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/StatementList.cpp.o
.PHONY : src/StatementList.cpp.o

src/StatementList.i: src/StatementList.cpp.i

.PHONY : src/StatementList.i

# target to preprocess a source file
src/StatementList.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/StatementList.cpp.i
.PHONY : src/StatementList.cpp.i

src/StatementList.s: src/StatementList.cpp.s

.PHONY : src/StatementList.s

# target to generate assembly for a file
src/StatementList.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/StatementList.cpp.s
.PHONY : src/StatementList.cpp.s

src/UnaryOperation.o: src/UnaryOperation.cpp.o

.PHONY : src/UnaryOperation.o

# target to build an object file
src/UnaryOperation.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/UnaryOperation.cpp.o
.PHONY : src/UnaryOperation.cpp.o

src/UnaryOperation.i: src/UnaryOperation.cpp.i

.PHONY : src/UnaryOperation.i

# target to preprocess a source file
src/UnaryOperation.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/UnaryOperation.cpp.i
.PHONY : src/UnaryOperation.cpp.i

src/UnaryOperation.s: src/UnaryOperation.cpp.s

.PHONY : src/UnaryOperation.s

# target to generate assembly for a file
src/UnaryOperation.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/UnaryOperation.cpp.s
.PHONY : src/UnaryOperation.cpp.s

src/VariableDeclaration.o: src/VariableDeclaration.cpp.o

.PHONY : src/VariableDeclaration.o

# target to build an object file
src/VariableDeclaration.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/VariableDeclaration.cpp.o
.PHONY : src/VariableDeclaration.cpp.o

src/VariableDeclaration.i: src/VariableDeclaration.cpp.i

.PHONY : src/VariableDeclaration.i

# target to preprocess a source file
src/VariableDeclaration.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/VariableDeclaration.cpp.i
.PHONY : src/VariableDeclaration.cpp.i

src/VariableDeclaration.s: src/VariableDeclaration.cpp.s

.PHONY : src/VariableDeclaration.s

# target to generate assembly for a file
src/VariableDeclaration.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/VariableDeclaration.cpp.s
.PHONY : src/VariableDeclaration.cpp.s

src/VariableDeclarationList.o: src/VariableDeclarationList.cpp.o

.PHONY : src/VariableDeclarationList.o

# target to build an object file
src/VariableDeclarationList.cpp.o:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/VariableDeclarationList.cpp.o
.PHONY : src/VariableDeclarationList.cpp.o

src/VariableDeclarationList.i: src/VariableDeclarationList.cpp.i

.PHONY : src/VariableDeclarationList.i

# target to preprocess a source file
src/VariableDeclarationList.cpp.i:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/VariableDeclarationList.cpp.i
.PHONY : src/VariableDeclarationList.cpp.i

src/VariableDeclarationList.s: src/VariableDeclarationList.cpp.s

.PHONY : src/VariableDeclarationList.s

# target to generate assembly for a file
src/VariableDeclarationList.cpp.s:
	$(MAKE) -f CMakeFiles/coreLibrary.dir/build.make CMakeFiles/coreLibrary.dir/src/VariableDeclarationList.cpp.s
.PHONY : src/VariableDeclarationList.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... decafCompiler"
	@echo "... intrinsics_gen"
	@echo "... coreLibrary"
	@echo "... flex_bison_output/lex.yy.o"
	@echo "... flex_bison_output/lex.yy.i"
	@echo "... flex_bison_output/lex.yy.s"
	@echo "... flex_bison_output/parser.tab.o"
	@echo "... flex_bison_output/parser.tab.i"
	@echo "... flex_bison_output/parser.tab.s"
	@echo "... src/ArgumentDeclaration.o"
	@echo "... src/ArgumentDeclaration.i"
	@echo "... src/ArgumentDeclaration.s"
	@echo "... src/ArgumentDeclarationList.o"
	@echo "... src/ArgumentDeclarationList.i"
	@echo "... src/ArgumentDeclarationList.s"
	@echo "... src/AssignmentStatement.o"
	@echo "... src/AssignmentStatement.i"
	@echo "... src/AssignmentStatement.s"
	@echo "... src/BinaryExpression.o"
	@echo "... src/BinaryExpression.i"
	@echo "... src/BinaryExpression.s"
	@echo "... src/Block.o"
	@echo "... src/Block.i"
	@echo "... src/Block.s"
	@echo "... src/BoolLiteral.o"
	@echo "... src/BoolLiteral.i"
	@echo "... src/BoolLiteral.s"
	@echo "... src/BreakStatement.o"
	@echo "... src/BreakStatement.i"
	@echo "... src/BreakStatement.s"
	@echo "... src/CalloutArg.o"
	@echo "... src/CalloutArg.i"
	@echo "... src/CalloutArg.s"
	@echo "... src/CalloutArgList.o"
	@echo "... src/CalloutArgList.i"
	@echo "... src/CalloutArgList.s"
	@echo "... src/CalloutMethod.o"
	@echo "... src/CalloutMethod.i"
	@echo "... src/CalloutMethod.s"
	@echo "... src/CharLiteral.o"
	@echo "... src/CharLiteral.i"
	@echo "... src/CharLiteral.s"
	@echo "... src/ContinueStatement.o"
	@echo "... src/ContinueStatement.i"
	@echo "... src/ContinueStatement.s"
	@echo "... src/Expression.o"
	@echo "... src/Expression.i"
	@echo "... src/Expression.s"
	@echo "... src/ExpressionList.o"
	@echo "... src/ExpressionList.i"
	@echo "... src/ExpressionList.s"
	@echo "... src/Field.o"
	@echo "... src/Field.i"
	@echo "... src/Field.s"
	@echo "... src/FieldDeclaration.o"
	@echo "... src/FieldDeclaration.i"
	@echo "... src/FieldDeclaration.s"
	@echo "... src/FieldDeclarationList.o"
	@echo "... src/FieldDeclarationList.i"
	@echo "... src/FieldDeclarationList.s"
	@echo "... src/FieldList.o"
	@echo "... src/FieldList.i"
	@echo "... src/FieldList.s"
	@echo "... src/ForStatement.o"
	@echo "... src/ForStatement.i"
	@echo "... src/ForStatement.s"
	@echo "... src/IdList.o"
	@echo "... src/IdList.i"
	@echo "... src/IdList.s"
	@echo "... src/IfStatement.o"
	@echo "... src/IfStatement.i"
	@echo "... src/IfStatement.s"
	@echo "... src/IntLiteral.o"
	@echo "... src/IntLiteral.i"
	@echo "... src/IntLiteral.s"
	@echo "... src/LLVMIRGenerator.o"
	@echo "... src/LLVMIRGenerator.i"
	@echo "... src/LLVMIRGenerator.s"
	@echo "... src/Location.o"
	@echo "... src/Location.i"
	@echo "... src/Location.s"
	@echo "... src/MethodDeclaration.o"
	@echo "... src/MethodDeclaration.i"
	@echo "... src/MethodDeclaration.s"
	@echo "... src/MethodDeclarationList.o"
	@echo "... src/MethodDeclarationList.i"
	@echo "... src/MethodDeclarationList.s"
	@echo "... src/MethodStatement.o"
	@echo "... src/MethodStatement.i"
	@echo "... src/MethodStatement.s"
	@echo "... src/NestedUnaryExpression.o"
	@echo "... src/NestedUnaryExpression.i"
	@echo "... src/NestedUnaryExpression.s"
	@echo "... src/Program.o"
	@echo "... src/Program.i"
	@echo "... src/Program.s"
	@echo "... src/ReturnExpression.o"
	@echo "... src/ReturnExpression.i"
	@echo "... src/ReturnExpression.s"
	@echo "... src/SimpleMethod.o"
	@echo "... src/SimpleMethod.i"
	@echo "... src/SimpleMethod.s"
	@echo "... src/StatementList.o"
	@echo "... src/StatementList.i"
	@echo "... src/StatementList.s"
	@echo "... src/UnaryOperation.o"
	@echo "... src/UnaryOperation.i"
	@echo "... src/UnaryOperation.s"
	@echo "... src/VariableDeclaration.o"
	@echo "... src/VariableDeclaration.i"
	@echo "... src/VariableDeclaration.s"
	@echo "... src/VariableDeclarationList.o"
	@echo "... src/VariableDeclarationList.i"
	@echo "... src/VariableDeclarationList.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

